package suresh.shoeshope.menu;

public enum Menus {
	Women,Kids,Men;
	
	public enum SubMenu{
		WOMEN_HEELS,
		WOMEN_SANDALS,
		WOMEN_SHOES,
		WOMEN_HEELS_HIGHHEELS,
		WOMEN_HEELS_LOWHEELS,
		WOMEN_HEELS_POINTEDHEELS,
		WOMEN_HEELS_WEDGEHEELS,
		WOMEN_SANDALS_REGULLAR,
		WOMEN_SANDALS_KITTEN,
		WOMEN_SHOES_CASUALSHOE,
		WOMEN_SHOES_SPORTSHOES,
		WOMEN_SHOES_FORMALSHOES,
		WOMEN_SHOES_ETHINICSHOES,
		MEN_SHOES,
		MEN_SNEAKERS,
		MEN_ATHELETICS,
		MEN_LOAFERS,
		MEN_SHOES_CASULASHOES,
		MEN_SHOES_FORMALSHOES,
		MEN_SHOES_SEMIFORMALS,
		MEN_SNEAKERS_REGULARS,
		MEN_ATHELETICS_OUTDOORANDHIKINGSHOES,
		MEN_ATHELETICS_RUNNINGSHOES,
		MEN_ATHELETICS_INDOORSPORTSHOES,
		MEN_ATHELETICS_TRANNINGSHOES,
		KIDS_BOYS,
		KIDS_BOYS_BOOTS,
		KIDS_BOYS_CASUALSHOE,
		KIDS_BOYS_FLIPFLOPS,
		KIDS_BOYS_SANDELS,
		KIDS_BOYS_SCHOOLSHOES,
		KIDS_BOYS_SPORTSHOES,
		KIDS_GIRLS,
		KIDS_GIRLS_SANDELS,
		KIDS_GIRLS_CLOGS,
		KIDS_GIRLS_FLATANDBELLIES,
		KIDS_GIRLS_SPORTSANDCASUALSHOES,
		NONE
	}

}
